name: phone_book
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #? Common
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^10.1.0
  #? API
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  #? Connection
  connectivity_plus: ^4.0.2
  #? Logger
  logger: ^2.0.1
  #? UI
  cached_network_image: ^3.2.3
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  easy_localization: ^3.0.2
  shimmer: ^3.0.0
  bot_toast: ^4.0.4
  pull_to_refresh: ^2.0.0
  after_layout: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:


  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/